#!/bin/bash
# See https://github.com/adriancooney/Taskfile for examples

# Sane error handling
set -e -o pipefail

### FUNCTIONS GO HERE
function default {
	: "Default task is help"
	help
}

function build {
	: "Build all versions"
	bazel build //:all
}

function view {
	: "view [[d]igital|[c]ookbook|[t]ested]"
	case "$1" in
		""|"d"|"digital"|"Digital")
			job="Cookbook-Digital"
			;;
		"c"|"cookbook")
			job="Cookbook"
			;;
		"t"|"tested"|"Tested")
			job="Cookbook-Tested"
			;;
	esac
	bazel run "//:${job}_view"
}

function deploy {
	: "Copy outputs to pi fileserver"
	bazel run //:publish
}

function release {
	: "Create a github release from the current commit, as long as it's tagged"
	build
	bazel run @github_release_api//:release \
		-l the-nick-of-time -t "$GITHUB_API_KEY" \
		-o the-nick-of-time -r Cookbook \
		-d $(git describe --tags --abbrev=0) \
		-c create
	bazel run @github_release_api//:release \
		-l the-nick-of-time -t "$GITHUB_API_KEY" \
		-o the-nick-of-time -r Cookbook \
		-d $(git describe --tags --abbrev=0) \
		-c upload bazel-bin/Cookbook-Tested.pdf bazel-bin/Cookbook-Digital.pdf bazel-bin/Cookbook.pdf
}

function new {
	: "Create a new recipe file interactively"
	bazel run //:new
}

function phone-sync {
	: "Share cookbooks to phone"
	build
	for name in Cookbook Cookbook-Digital Cookbook-Tested ; do
		kdeconnect-cli --share "bazel-bin/${name}.pdf" --name "$PHONE"
	done
}

### /FUNCTIONS GO HERE

function help {
    : "Auto-generate a list of tasks"
    compgen -A function | while read name ; do
		paste <(printf '%s' "$name") <(type "$name" | sed -En 's/^[[:space:]]*: "(.*)";/\1/p')
    done
}

"${@:-default}"
