#!/bin/bash
# See https://github.com/adriancooney/Taskfile for examples

# Sane error handling 
set -e -o pipefail

### FUNCTIONS GO HERE
function default {
	: "Default task is help"
	help
}

function build {
	: "Build all versions"
	bazel build //:all
}

function view {
	: "view [[d]igital|[c]ookbook|[t]ested]"
	case "$1" in
		""|"d"|"digital"|"Digital")
			job="Cookbook-Digital" 
			;;
		"c"|"cookbook")
			job="Cookbook"
			;;
		"t"|"tested"|"Tested")
			job="Cookbook-Tested"
			;;
	esac
	bazel run "//:${job}_view"
}

function release {
	: "Create a github release from the current commit, as long as it's tagged"
	build
	./github-release-api/github_release_manager.sh \
		-l the-nick-of-time -t $(cat ~/code/github_api_key) \
		-o the-nick-of-time -r Cookbook \
		-d $(git describe --tags --abbrev=0) \
		-c create
	./github-release-api/github_release_manager.sh \
		-l the-nick-of-time -t $(cat ~/code/github_api_key) \
		-o the-nick-of-time -r Cookbook \
		-d $(git describe --tags --abbrev=0) \
		-c upload bazel-bin/Cookbook-Tested.pdf bazel-bin/Cookbook-Digital.pdf bazel-bin/Cookbook.pdf
}

### /FUNCTIONS GO HERE

function help {
    : "Auto-generate a list of tasks"
    set +x
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | while read name ; do
		paste <(printf '%s' "$name") <(type "$name" | sed -n '4p')
    done
}

"${@:-default}"
